# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import orchestrator_pb2 as orchestrator__pb2


class OrchestratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDevice = channel.unary_unary(
                '/orchestrator.Orchestrator/RegisterDevice',
                request_serializer=orchestrator__pb2.CSR.SerializeToString,
                response_deserializer=orchestrator__pb2.Certificate.FromString,
                )
        self.GetRound = channel.unary_unary(
                '/orchestrator.Orchestrator/GetRound',
                request_serializer=orchestrator__pb2.DeviceId.SerializeToString,
                response_deserializer=orchestrator__pb2.RoundMetadata.FromString,
                )
        self.SubmitReceipt = channel.unary_unary(
                '/orchestrator.Orchestrator/SubmitReceipt',
                request_serializer=orchestrator__pb2.Receipt.SerializeToString,
                response_deserializer=orchestrator__pb2.Ack.FromString,
                )
        self.RequestEnrollment = channel.unary_unary(
                '/orchestrator.Orchestrator/RequestEnrollment',
                request_serializer=orchestrator__pb2.EnrollmentRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.EnrollmentRequestAck.FromString,
                )
        self.EnrollDevice = channel.unary_unary(
                '/orchestrator.Orchestrator/EnrollDevice',
                request_serializer=orchestrator__pb2.EnrollRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.EnrollResponse.FromString,
                )


class OrchestratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestEnrollment(self, request, context):
        """Phase 1 of enrollment: client announces itself; server generates a
        per-device OTP and prints it to the admin console.  No OTP is needed
        to call this RPC — only device_pubkey and csr.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrollDevice(self, request, context):
        """Phase 2 of enrollment: client submits the OTP obtained out-of-band
        from the administrator.  Server verifies OTP, signs CSR, returns cert.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDevice,
                    request_deserializer=orchestrator__pb2.CSR.FromString,
                    response_serializer=orchestrator__pb2.Certificate.SerializeToString,
            ),
            'GetRound': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRound,
                    request_deserializer=orchestrator__pb2.DeviceId.FromString,
                    response_serializer=orchestrator__pb2.RoundMetadata.SerializeToString,
            ),
            'SubmitReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitReceipt,
                    request_deserializer=orchestrator__pb2.Receipt.FromString,
                    response_serializer=orchestrator__pb2.Ack.SerializeToString,
            ),
            'RequestEnrollment': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestEnrollment,
                    request_deserializer=orchestrator__pb2.EnrollmentRequest.FromString,
                    response_serializer=orchestrator__pb2.EnrollmentRequestAck.SerializeToString,
            ),
            'EnrollDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrollDevice,
                    request_deserializer=orchestrator__pb2.EnrollRequest.FromString,
                    response_serializer=orchestrator__pb2.EnrollResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.Orchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Orchestrator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orchestrator.Orchestrator/RegisterDevice',
            orchestrator__pb2.CSR.SerializeToString,
            orchestrator__pb2.Certificate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orchestrator.Orchestrator/GetRound',
            orchestrator__pb2.DeviceId.SerializeToString,
            orchestrator__pb2.RoundMetadata.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orchestrator.Orchestrator/SubmitReceipt',
            orchestrator__pb2.Receipt.SerializeToString,
            orchestrator__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestEnrollment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orchestrator.Orchestrator/RequestEnrollment',
            orchestrator__pb2.EnrollmentRequest.SerializeToString,
            orchestrator__pb2.EnrollmentRequestAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnrollDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orchestrator.Orchestrator/EnrollDevice',
            orchestrator__pb2.EnrollRequest.SerializeToString,
            orchestrator__pb2.EnrollResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
